// Tripqo bestemmingen-database — 43 bestemmingen
var DEST = {
  // ===== ZON & STRAND =====
  BCN:{b:"Barcelona, Spanje",sfeer:"zon",tier:"kort",temp:"26°C",vt:"2 uur",kl:"lichte zomerkleding & zwemkleding",taal:"Spaans",ht:110,hotel:"Hotel Arts Barcelona",hstars:"4.6",dagen:["Barceloneta strand & verkenning","Sagrada Família & Gothic Quarter","Dagtrip naar Sitges"],acts:[{n:"Sagrada Família skip-the-line tour",s:"4.8",r:"12.400",p:49,cat:"cultuur"},{n:"Barceloneta sunset cruise",s:"4.7",r:"3.200",p:35,cat:"boot"},{n:"Gothic Quarter streetfood tour",s:"4.9",r:"8.100",p:42,cat:"eten"}]},
  LIS:{b:"Lissabon, Portugal",sfeer:"zon",tier:"mid",temp:"24°C",vt:"2.5 uur",kl:"lichte kleding, vest voor de avond",taal:"Portugees",ht:90,hotel:"Memmo Alfama",hstars:"4.5",dagen:["Alfama wijk & miradouros","Dagtrip Sintra & kastelen","Belém toren & pastéis de nata"],acts:[{n:"Privé tuk-tuk tour door Alfama",s:"4.9",r:"6.800",p:38,cat:"tour"},{n:"Fado show met diner",s:"4.8",r:"4.300",p:55,cat:"cultuur"},{n:"Sintra & Cascais dagtrip",s:"4.7",r:"9.200",p:45,cat:"dagtrip"}]},
  AGP:{b:"Malaga, Spanje",sfeer:"zon",tier:"mid",temp:"28°C",vt:"3 uur",kl:"zomerkleding & zonnebrand",taal:"Spaans",ht:85,hotel:"Vincci Selección Posada del Patio",hstars:"4.4",dagen:["Picasso museum & centrum","Strand & tapas avond","Dagtrip naar Nerja & grotten"],acts:[{n:"Nerja grotten dagtrip",s:"4.6",r:"2.800",p:42,cat:"natuur"},{n:"Malaga wijn & tapas tour",s:"4.8",r:"1.900",p:55,cat:"eten"},{n:"Flamenco show",s:"4.7",r:"3.400",p:35,cat:"cultuur"}]},
  JTR:{b:"Santorini, Griekenland",sfeer:"zon",tier:"mid",temp:"27°C",vt:"3.5 uur",kl:"lichte zomerkleding & zonnebrand",taal:"Grieks",ht:160,hotel:"Katikies Santorini",hstars:"4.8",dagen:["Oia & zonsondergang","Zwarte strand Perissa","Wijnproeverij & caldera"],acts:[{n:"Catamaran sunset cruise",s:"4.9",r:"5.600",p:95,cat:"boot"},{n:"Wijnproeverij Santorini",s:"4.8",r:"3.100",p:65,cat:"wijn"},{n:"Oia fotografietour",s:"4.7",r:"2.200",p:48,cat:"tour"}]},
  DBV:{b:"Dubrovnik, Kroatië",sfeer:"zon",tier:"mid",temp:"26°C",vt:"2.5 uur",kl:"lichte kleding & comfortabele schoenen",taal:"Kroatisch",ht:130,hotel:"Hotel Excelsior Dubrovnik",hstars:"4.6",dagen:["Oude stadsmuren wandeling","Eilandhoppen per boot","Lokale restaurants & vis"],acts:[{n:"Game of Thrones tour",s:"4.8",r:"7.400",p:42,cat:"tour"},{n:"Eilandhoppen speedboot",s:"4.9",r:"4.100",p:75,cat:"boot"},{n:"Kabelbaan & stadsmuren",s:"4.7",r:"6.200",p:35,cat:"cultuur"}]},
  PMI:{b:"Mallorca, Spanje",sfeer:"zon",tier:"mid",temp:"27°C",vt:"2.5 uur",kl:"zomerkleding & zwemkleding",taal:"Spaans",ht:100,hotel:"Hotel Cort Palma",hstars:"4.5",dagen:["Palma kathedraal & oude stad","Stranddag Cala Major","Serra de Tramuntana dagtrip"],acts:[{n:"Boottocht langs de kust",s:"4.8",r:"4.900",p:55,cat:"boot"},{n:"Tramuntana wandeltocht",s:"4.7",r:"2.300",p:40,cat:"natuur"},{n:"Palma tapas tour",s:"4.8",r:"3.100",p:48,cat:"eten"}]},
  FAO:{b:"Algarve, Portugal",sfeer:"zon",tier:"mid",temp:"26°C",vt:"3 uur",kl:"zomerkleding & zwemkleding",taal:"Portugees",ht:95,hotel:"Tivoli Carvoeiro",hstars:"4.6",dagen:["Benagil grot & stranden","Lagos oude stad","Kliffenwandeling Ponta da Piedade"],acts:[{n:"Benagil grot boottocht",s:"4.9",r:"8.200",p:35,cat:"boot"},{n:"Dolfijnen spotten",s:"4.7",r:"3.400",p:45,cat:"natuur"},{n:"Algarve wijntour",s:"4.8",r:"1.900",p:55,cat:"wijn"}]},
  IBZ:{b:"Ibiza, Spanje",sfeer:"zon",tier:"mid",temp:"27°C",vt:"2.5 uur",kl:"zomerkleding & feestoutfit",taal:"Spaans",ht:140,hotel:"Ushuaïa Ibiza",hstars:"4.5",dagen:["Stranden & beachclubs","Oude stad Dalt Vila","Sunset bij Es Vedrà"],acts:[{n:"Boottocht & snorkelen",s:"4.8",r:"5.400",p:65,cat:"boot"},{n:"Beachclub dagpas",s:"4.6",r:"7.200",p:80,cat:"strand"},{n:"Dalt Vila wandeltour",s:"4.7",r:"2.100",p:30,cat:"cultuur"}]},
  TFS:{b:"Tenerife, Spanje",sfeer:"zon",tier:"mid",temp:"25°C",vt:"4.5 uur",kl:"zomerkleding & zwemkleding",taal:"Spaans",ht:95,hotel:"Hotel Botánico",hstars:"4.6",dagen:["Teide vulkaan dagtrip","Stranden van Costa Adeje","Walvissen spotten"],acts:[{n:"Teide kabelbaan & wandeling",s:"4.8",r:"9.100",p:55,cat:"natuur"},{n:"Walvissen & dolfijnen tour",s:"4.7",r:"6.300",p:48,cat:"boot"},{n:"Sterrenkijken bij Teide",s:"4.9",r:"3.200",p:65,cat:"natuur"}]},
  VLC:{b:"Valencia, Spanje",sfeer:"zon",tier:"mid",temp:"26°C",vt:"2.5 uur",kl:"zomerkleding & zonnebrand",taal:"Spaans",ht:90,hotel:"Caro Hotel Valencia",hstars:"4.6",dagen:["Stad van Kunst & Wetenschap","Strand Malvarrosa","Oude stad & Central Market"],acts:[{n:"Paella kookworkshop",s:"4.9",r:"5.100",p:65,cat:"eten"},{n:"Oceanogràfic aquarium",s:"4.7",r:"9.800",p:38,cat:"cultuur"},{n:"Fietstour door Valencia",s:"4.8",r:"2.900",p:28,cat:"tour"}]},

  // ===== STAD & CULTUUR =====
  FCO:{b:"Rome, Italië",sfeer:"stad",tier:"mid",temp:"22°C",vt:"2.5 uur",kl:"comfortabele schoenen & laagjes",taal:"Italiaans",ht:120,hotel:"Hotel Campo de' Fiori",hstars:"4.4",dagen:["Colosseum & Forum Romanum","Vaticaan & Sixtijnse Kapel","Trastevere & restaurants"],acts:[{n:"Colosseum skip-the-line & underground",s:"4.8",r:"18.900",p:55,cat:"cultuur"},{n:"Vaticaan vroegboektour",s:"4.9",r:"22.400",p:65,cat:"cultuur"},{n:"Rome bij nacht food tour",s:"4.8",r:"7.600",p:48,cat:"eten"}]},
  PRG:{b:"Praag, Tsjechië",sfeer:"stad",tier:"kort",temp:"18°C",vt:"1.5 uur",kl:"laagjes & comfortabele schoenen",taal:"Tsjechisch",ht:70,hotel:"Augustine Hotel",hstars:"4.6",dagen:["Praagse Burcht & Karelsbrug","Oude Stad & astronomische klok","Joods kwartier & bierproeverij"],acts:[{n:"Privérondleiding Praagse Burcht",s:"4.9",r:"4.200",p:35,cat:"cultuur"},{n:"Tsjechische bierproeverij",s:"4.7",r:"6.800",p:28,cat:"eten"},{n:"Moldau zonsondergang cruise",s:"4.6",r:"3.100",p:22,cat:"boot"}]},
  VIE:{b:"Wenen, Oostenrijk",sfeer:"stad",tier:"kort",temp:"20°C",vt:"1.5 uur",kl:"nette casual kleding",taal:"Duits",ht:100,hotel:"Hotel Sacher Wien",hstars:"4.7",dagen:["Schönbrunn paleis & tuinen","Kunsthistorisch Museum","Prater & Wiener Schnitzel"],acts:[{n:"Schönbrunn paleis privétour",s:"4.8",r:"9.300",p:45,cat:"cultuur"},{n:"Weense filharmonie concert",s:"4.9",r:"5.600",p:75,cat:"muziek"},{n:"Koffiehuistour met patisserie",s:"4.7",r:"4.100",p:38,cat:"eten"}]},
  BUD:{b:"Budapest, Hongarije",sfeer:"stad",tier:"kort",temp:"21°C",vt:"2 uur",kl:"casual & badkleding",taal:"Hongaars",ht:85,hotel:"Párisi Udvar Hotel",hstars:"4.7",dagen:["Széchenyi thermaal bad","Boedapest ruïnekroegen","Margaretha-eiland & wellness"],acts:[{n:"Széchenyi spa VIP dagpakket",s:"4.8",r:"9.400",p:45,cat:"spa"},{n:"Ruin bar pub crawl",s:"4.7",r:"14.200",p:28,cat:"nachtleven"},{n:"Riviercruise bij nacht",s:"4.8",r:"8.900",p:32,cat:"boot"}]},
  CPH:{b:"Kopenhagen, Denemarken",sfeer:"stad",tier:"kort",temp:"17°C",vt:"1.5 uur",kl:"laagjes & regenjas",taal:"Deens",ht:130,hotel:"Hotel Sanders",hstars:"4.7",dagen:["Nyhavn & binnenstad","Tivoli pretpark","Christiania & design"],acts:[{n:"Kanaalrondvaart",s:"4.7",r:"7.200",p:32,cat:"boot"},{n:"Tivoli toegang",s:"4.8",r:"12.100",p:42,cat:"cultuur"},{n:"Deense food & design tour",s:"4.8",r:"2.800",p:58,cat:"eten"}]},
  EDI:{b:"Edinburgh, Schotland",sfeer:"stad",tier:"kort",temp:"15°C",vt:"1.5 uur",kl:"laagjes & regenjas",taal:"Engels",ht:110,hotel:"The Balmoral",hstars:"4.7",dagen:["Edinburgh Castle & Royal Mile","Arthur's Seat wandeling","Whisky proeverij"],acts:[{n:"Edinburgh Castle tour",s:"4.8",r:"9.600",p:38,cat:"cultuur"},{n:"Schotse whisky proeverij",s:"4.8",r:"4.200",p:55,cat:"eten"},{n:"Highlands dagtrip",s:"4.9",r:"11.400",p:75,cat:"dagtrip"}]},
  BER:{b:"Berlijn, Duitsland",sfeer:"stad",tier:"kort",temp:"19°C",vt:"1.5 uur",kl:"casual & laagjes",taal:"Duits",ht:95,hotel:"Hotel Adlon Kempinski",hstars:"4.6",dagen:["Brandenburger Tor & Reichstag","Museumeiland","East Side Gallery & nachtleven"],acts:[{n:"Berlijnse muur & geschiedenis tour",s:"4.8",r:"11.200",p:35,cat:"cultuur"},{n:"Museumeiland toegang",s:"4.7",r:"8.400",p:42,cat:"cultuur"},{n:"Streetfood & craft beer tour",s:"4.8",r:"3.900",p:48,cat:"eten"}]},
  PAR:{b:"Parijs, Frankrijk",sfeer:"stad",tier:"kort",temp:"20°C",vt:"1.5 uur",kl:"nette casual kleding",taal:"Frans",ht:140,hotel:"Hôtel Le Bristol",hstars:"4.8",dagen:["Eiffeltoren & Champs-Élysées","Louvre & Montmartre","Seine cruise & patisserie"],acts:[{n:"Louvre skip-the-line tour",s:"4.8",r:"21.300",p:55,cat:"cultuur"},{n:"Eiffeltoren toegang top",s:"4.7",r:"18.600",p:48,cat:"cultuur"},{n:"Seine diner cruise",s:"4.8",r:"9.200",p:85,cat:"boot"}]},
  MAD:{b:"Madrid, Spanje",sfeer:"stad",tier:"mid",temp:"24°C",vt:"2.5 uur",kl:"lichte kleding",taal:"Spaans",ht:100,hotel:"Hotel Único Madrid",hstars:"4.6",dagen:["Prado museum & Retiro park","Royal Palace","Tapas in La Latina"],acts:[{n:"Prado museum tour",s:"4.8",r:"9.700",p:42,cat:"cultuur"},{n:"Tapas & wijn tour",s:"4.9",r:"5.300",p:58,cat:"eten"},{n:"Flamenco show Madrid",s:"4.7",r:"4.800",p:45,cat:"cultuur"}]},
  FLR:{b:"Florence, Italië",sfeer:"stad",tier:"mid",temp:"23°C",vt:"2 uur",kl:"comfortabele schoenen & laagjes",taal:"Italiaans",ht:130,hotel:"Hotel Lungarno",hstars:"4.7",dagen:["Uffizi & David van Michelangelo","Ponte Vecchio & Oltrarno","Toscaanse heuvels dagtrip"],acts:[{n:"Uffizi galerij tour",s:"4.8",r:"14.200",p:55,cat:"cultuur"},{n:"Toscane wijntour",s:"4.9",r:"8.900",p:85,cat:"wijn"},{n:"Florence food walking tour",s:"4.8",r:"6.100",p:48,cat:"eten"}]},

  // ===== NATUUR & AVONTUUR =====
  KEF:{b:"Reykjavik, IJsland",sfeer:"natuur",tier:"mid",temp:"12°C",vt:"3 uur",kl:"warme lagen & waterdichte jas",taal:"IJslands",ht:130,hotel:"Ion Adventure Hotel",hstars:"4.5",dagen:["Gouden Cirkel & geisers","Snorkelen bij Silfra","Noorderlicht zoeken"],acts:[{n:"Silfra snorkel tussen platen",s:"4.9",r:"8.400",p:79,cat:"avontuur"},{n:"Gouden Cirkel privétour",s:"4.8",r:"12.600",p:95,cat:"natuur"},{n:"Noorderlicht zoektocht",s:"4.7",r:"9.800",p:65,cat:"natuur"}]},
  BGO:{b:"Bergen, Noorwegen",sfeer:"natuur",tier:"kort",temp:"15°C",vt:"2 uur",kl:"waterdichte kleding & stevige schoenen",taal:"Noors",ht:110,hotel:"Hotel Oleana Bergen",hstars:"4.5",dagen:["Fjordcruise Hardangerfjord","Fløibanen bergwandeling","Hanzestad & vismarkt"],acts:[{n:"Hardangerfjord cruise",s:"4.8",r:"5.600",p:55,cat:"boot"},{n:"Fløibanen & bergwandeling",s:"4.7",r:"7.200",p:35,cat:"natuur"},{n:"Bergen foodtour",s:"4.6",r:"3.400",p:45,cat:"eten"}]},
  INN:{b:"Innsbruck, Oostenrijk",sfeer:"natuur",tier:"kort",temp:"16°C",vt:"1.5 uur",kl:"laagjes & stevige schoenen",taal:"Duits",ht:100,hotel:"Hotel Innsbruck",hstars:"4.5",dagen:["Nordkette kabelbaan","Historisch centrum","Swarovski Kristalwerelden"],acts:[{n:"Nordkette kabelbaan & wandeling",s:"4.8",r:"4.600",p:42,cat:"natuur"},{n:"Swarovski museum tour",s:"4.6",r:"3.200",p:28,cat:"cultuur"},{n:"Alpen e-bike tour",s:"4.7",r:"1.800",p:55,cat:"avontuur"}]},
  GVA:{b:"Genève, Zwitserland",sfeer:"natuur",tier:"kort",temp:"18°C",vt:"1.5 uur",kl:"laagjes & wandelschoenen",taal:"Frans",ht:150,hotel:"Hotel Beau-Rivage",hstars:"4.7",dagen:["Meer van Genève & Jet d'Eau","Mont Blanc uitzicht","Oude stad & chocolade"],acts:[{n:"Mont Blanc dagtrip",s:"4.9",r:"6.800",p:95,cat:"natuur"},{n:"Zwitserse chocolade tour",s:"4.8",r:"3.400",p:48,cat:"eten"},{n:"Meercruise Genève",s:"4.7",r:"4.100",p:42,cat:"boot"}]},
  TRD:{b:"Trondheim, Noorwegen",sfeer:"natuur",tier:"mid",temp:"13°C",vt:"2.5 uur",kl:"warme waterdichte kleding",taal:"Noors",ht:120,hotel:"Britannia Hotel",hstars:"4.7",dagen:["Nidaros kathedraal","Fjord kajakken","Noorderlicht (seizoen)"],acts:[{n:"Fjord kajaktocht",s:"4.8",r:"2.900",p:65,cat:"avontuur"},{n:"Nidaros kathedraal tour",s:"4.7",r:"3.800",p:32,cat:"cultuur"},{n:"Wildlife safari",s:"4.6",r:"1.700",p:75,cat:"natuur"}]},

  // ===== RELAXED & SPA =====
  OPO:{b:"Porto, Portugal",sfeer:"relaxed",tier:"mid",temp:"22°C",vt:"2.5 uur",kl:"lichte kleding, vest voor de avond",taal:"Portugees",ht:95,hotel:"The Yeatman Hotel",hstars:"4.8",dagen:["Ribeira & Douro rivier","Portwijnproeverij","Livraria Lello & strand"],acts:[{n:"Douro vallei wijnproeverij",s:"4.9",r:"6.200",p:65,cat:"wijn"},{n:"Porto cultuurwandeling",s:"4.7",r:"4.800",p:32,cat:"cultuur"},{n:"Zonsondergang boottocht",s:"4.8",r:"5.600",p:28,cat:"boot"}]},
  MLA:{b:"Valletta, Malta",sfeer:"relaxed",tier:"mid",temp:"25°C",vt:"3 uur",kl:"lichte zomerkleding",taal:"Maltees & Engels",ht:90,hotel:"The Phoenicia Malta",hstars:"4.6",dagen:["Valletta historisch centrum","Blauw Lagoon op Comino","Mdina: de stille stad"],acts:[{n:"Comino & Blauw Lagoon boottocht",s:"4.8",r:"6.700",p:45,cat:"boot"},{n:"Mdina & Rabat tour",s:"4.7",r:"3.900",p:35,cat:"cultuur"},{n:"Valletta food tour",s:"4.8",r:"2.400",p:48,cat:"eten"}]},
  NAP:{b:"Napels, Italië",sfeer:"relaxed",tier:"mid",temp:"24°C",vt:"2.5 uur",kl:"lichte kleding & comfortabele schoenen",taal:"Italiaans",ht:95,hotel:"Grand Hotel Vesuvio",hstars:"4.6",dagen:["Historisch centrum & pizza","Pompeii dagtrip","Amalfikust uitstapje"],acts:[{n:"Pompeii skip-the-line tour",s:"4.8",r:"11.200",p:55,cat:"cultuur"},{n:"Amalfikust dagtrip",s:"4.9",r:"8.400",p:75,cat:"dagtrip"},{n:"Pizza workshop Napels",s:"4.8",r:"3.600",p:48,cat:"eten"}]},
  SPU:{b:"Split, Kroatië",sfeer:"relaxed",tier:"mid",temp:"26°C",vt:"2.5 uur",kl:"zomerkleding & zwemkleding",taal:"Kroatisch",ht:105,hotel:"Hotel Park Split",hstars:"4.6",dagen:["Diocletianus paleis","Eilandhoppen Hvar & Brač","Strand & zonsondergang"],acts:[{n:"Hvar & blauwe grot boottocht",s:"4.9",r:"7.800",p:75,cat:"boot"},{n:"Diocletianus paleis tour",s:"4.7",r:"4.200",p:32,cat:"cultuur"},{n:"Kroatische wijn & olijfolie tour",s:"4.8",r:"2.100",p:55,cat:"wijn"}]},
  NCE:{b:"Nice, Frankrijk",sfeer:"relaxed",tier:"mid",temp:"25°C",vt:"2 uur",kl:"lichte elegante kleding",taal:"Frans",ht:135,hotel:"Hotel Negresco",hstars:"4.6",dagen:["Promenade des Anglais","Monaco & Eze dagtrip","Oude stad & markten"],acts:[{n:"Monaco & Monte Carlo dagtrip",s:"4.8",r:"6.400",p:65,cat:"dagtrip"},{n:"Côte d'Azur boottocht",s:"4.9",r:"4.900",p:85,cat:"boot"},{n:"Nice food market tour",s:"4.7",r:"3.200",p:42,cat:"eten"}]},
  VCE:{b:"Venetië, Italië",sfeer:"relaxed",tier:"mid",temp:"23°C",vt:"2 uur",kl:"comfortabele schoenen & laagjes",taal:"Italiaans",ht:140,hotel:"Hotel Danieli",hstars:"4.7",dagen:["San Marco & Dogenpaleis","Gondelvaart & Rialto","Murano & Burano eilanden"],acts:[{n:"Gondelvaart privé",s:"4.8",r:"15.600",p:85,cat:"boot"},{n:"Dogenpaleis skip-the-line",s:"4.7",r:"9.200",p:48,cat:"cultuur"},{n:"Murano & Burano dagtrip",s:"4.8",r:"6.700",p:55,cat:"dagtrip"}]},

  // ===== MIDDEN-OOSTEN & NOORD-AFRIKA =====
  RAK:{b:"Marrakech, Marokko",sfeer:"zon",tier:"ver",temp:"30°C",vt:"3.5 uur",kl:"lichte kleding & bedekkende outfit voor de medina",taal:"Arabisch & Frans",ht:90,hotel:"La Mamounia",hstars:"4.8",dagen:["Medina & souks","Jardin Majorelle","Atlasgebergte dagtrip"],acts:[{n:"Atlasgebergte & Berberdorpen",s:"4.8",r:"7.600",p:55,cat:"natuur"},{n:"Marrakech food & souk tour",s:"4.9",r:"5.400",p:42,cat:"eten"},{n:"Woestijn quad & kameel",s:"4.7",r:"4.800",p:65,cat:"avontuur"}]},
  HRG:{b:"Hurghada, Egypte",sfeer:"zon",tier:"ver",temp:"32°C",vt:"5 uur",kl:"zomerkleding & snorkelspullen",taal:"Arabisch",ht:75,hotel:"Steigenberger Al Dau Beach",hstars:"4.6",dagen:["Rode Zee snorkelen","Woestijnsafari","Giftun eiland dagtrip"],acts:[{n:"Rode Zee duik & snorkel",s:"4.8",r:"9.200",p:55,cat:"water"},{n:"Woestijn quad safari",s:"4.7",r:"6.800",p:48,cat:"avontuur"},{n:"Giftun eiland boottocht",s:"4.8",r:"5.100",p:42,cat:"boot"}]},
  CAI:{b:"Caïro, Egypte",sfeer:"stad",tier:"ver",temp:"30°C",vt:"4.5 uur",kl:"lichte bedekkende kleding",taal:"Arabisch",ht:80,hotel:"Marriott Mena House",hstars:"4.7",dagen:["Piramides van Gizeh & Sfinx","Egyptisch Museum","Khan el-Khalili bazaar"],acts:[{n:"Piramides & Sfinx privétour",s:"4.9",r:"14.300",p:65,cat:"cultuur"},{n:"Egyptisch Museum tour",s:"4.8",r:"8.700",p:42,cat:"cultuur"},{n:"Nijl dinercruise",s:"4.7",r:"6.200",p:55,cat:"boot"}]},
  DXB:{b:"Dubai, VAE",sfeer:"zon",tier:"ver",temp:"34°C",vt:"6.5 uur",kl:"lichte kleding & badkleding",taal:"Arabisch & Engels",ht:160,hotel:"Atlantis The Palm",hstars:"4.7",dagen:["Burj Khalifa & Dubai Mall","Woestijnsafari","Palm Jumeirah & strand"],acts:[{n:"Burj Khalifa top toegang",s:"4.8",r:"22.100",p:55,cat:"cultuur"},{n:"Woestijnsafari met diner",s:"4.9",r:"18.400",p:75,cat:"avontuur"},{n:"Dubai Marina yacht tour",s:"4.8",r:"7.300",p:95,cat:"boot"}]},
  AUH:{b:"Abu Dhabi, VAE",sfeer:"zon",tier:"ver",temp:"34°C",vt:"6.5 uur",kl:"lichte kleding & badkleding",taal:"Arabisch & Engels",ht:150,hotel:"Emirates Palace",hstars:"4.8",dagen:["Sheikh Zayed Moskee","Louvre Abu Dhabi","Yas Island & Ferrari World"],acts:[{n:"Sheikh Zayed Moskee tour",s:"4.9",r:"16.700",p:45,cat:"cultuur"},{n:"Ferrari World toegang",s:"4.7",r:"11.200",p:85,cat:"avontuur"},{n:"Mangrove kajaktocht",s:"4.8",r:"3.900",p:65,cat:"natuur"}]},
  AYT:{b:"Antalya, Turkije",sfeer:"zon",tier:"mid",temp:"29°C",vt:"4 uur",kl:"zomerkleding & zwemkleding",taal:"Turks",ht:80,hotel:"Akra Hotel Antalya",hstars:"4.5",dagen:["Oude stad Kaleiçi","Stranden & watervallen","Antieke stad Perge"],acts:[{n:"Boottocht langs de kust",s:"4.8",r:"7.600",p:38,cat:"boot"},{n:"Düden watervallen tour",s:"4.7",r:"4.200",p:28,cat:"natuur"},{n:"Turks bad & hammam",s:"4.8",r:"5.900",p:35,cat:"spa"}]},
  IST:{b:"Istanbul, Turkije",sfeer:"stad",tier:"mid",temp:"23°C",vt:"3.5 uur",kl:"laagjes & bedekkende kleding voor moskeeën",taal:"Turks",ht:95,hotel:"Çırağan Palace Kempinski",hstars:"4.8",dagen:["Hagia Sophia & Blauwe Moskee","Grote Bazaar","Bosporus cruise"],acts:[{n:"Hagia Sophia & paleis tour",s:"4.9",r:"15.800",p:48,cat:"cultuur"},{n:"Bosporus dinercruise",s:"4.8",r:"9.700",p:55,cat:"boot"},{n:"Turkse hammam ervaring",s:"4.7",r:"6.400",p:42,cat:"spa"}]},

  // ===== EXTRA EILANDEN / STEDEN =====
  CFU:{b:"Corfu, Griekenland",sfeer:"zon",tier:"mid",temp:"27°C",vt:"3 uur",kl:"zomerkleding & zwemkleding",taal:"Grieks",ht:90,hotel:"Corfu Imperial",hstars:"4.7",dagen:["Oude stad Corfu","Paleokastritsa stranden","Eilandtour per boot"],acts:[{n:"Eilandhoppen boottocht",s:"4.8",r:"4.600",p:55,cat:"boot"},{n:"Corfu food & wijn tour",s:"4.7",r:"2.300",p:48,cat:"eten"},{n:"Achilleion paleis tour",s:"4.6",r:"3.100",p:32,cat:"cultuur"}]},
  RHO:{b:"Rhodos, Griekenland",sfeer:"zon",tier:"mid",temp:"28°C",vt:"3.5 uur",kl:"zomerkleding & zonnebrand",taal:"Grieks",ht:95,hotel:"Rodos Palace",hstars:"4.5",dagen:["Middeleeuwse oude stad","Lindos akropolis","Stranden & baaien"],acts:[{n:"Lindos & akropolis tour",s:"4.8",r:"5.700",p:42,cat:"cultuur"},{n:"Symi eiland boottocht",s:"4.9",r:"4.300",p:65,cat:"boot"},{n:"Rhodos oude stad food tour",s:"4.7",r:"2.800",p:45,cat:"eten"}]},
  CHQ:{b:"Kreta, Griekenland",sfeer:"zon",tier:"mid",temp:"27°C",vt:"3.5 uur",kl:"zomerkleding & zwemkleding",taal:"Grieks",ht:90,hotel:"Domes Noruz Chania",hstars:"4.7",dagen:["Chania oude haven","Samaria kloof wandeling","Elafonissi roze strand"],acts:[{n:"Samaria kloof wandeling",s:"4.8",r:"6.900",p:55,cat:"natuur"},{n:"Elafonissi strand dagtrip",s:"4.9",r:"8.200",p:48,cat:"strand"},{n:"Kretenzische food tour",s:"4.8",r:"3.400",p:45,cat:"eten"}]},
  ATH:{b:"Athene, Griekenland",sfeer:"stad",tier:"mid",temp:"26°C",vt:"3.5 uur",kl:"lichte kleding & comfortabele schoenen",taal:"Grieks",ht:95,hotel:"Hotel Grande Bretagne",hstars:"4.7",dagen:["Akropolis & Parthenon","Plaka wijk","Dagtrip Kaap Sounion"],acts:[{n:"Akropolis skip-the-line tour",s:"4.9",r:"19.400",p:48,cat:"cultuur"},{n:"Athene food & markt tour",s:"4.8",r:"6.700",p:45,cat:"eten"},{n:"Kaap Sounion zonsondergang",s:"4.7",r:"4.200",p:55,cat:"dagtrip"}]},
  ZRH:{b:"Zürich, Zwitserland",sfeer:"stad",tier:"kort",temp:"19°C",vt:"1.5 uur",kl:"nette casual & laagjes",taal:"Duits",ht:155,hotel:"Baur au Lac",hstars:"4.8",dagen:["Oude stad & Bahnhofstrasse","Meer van Zürich","Uetliberg uitzicht"],acts:[{n:"Zürichmeer cruise",s:"4.7",r:"5.200",p:42,cat:"boot"},{n:"Zwitserse chocolade workshop",s:"4.9",r:"4.100",p:65,cat:"eten"},{n:"Uetliberg wandeling",s:"4.6",r:"2.300",p:28,cat:"natuur"}]}
};

var FALLBACK = {
  zon:['BCN','LIS','AGP','PMI','FAO','VLC','JTR','DBV','IBZ','TFS','CFU','RHO','CHQ','AYT'],
  stad:['FCO','PRG','VIE','BUD','CPH','EDI','BER','PAR','MAD','FLR','ATH','ZRH','IST'],
  natuur:['KEF','BGO','INN','GVA','TRD'],
  relaxed:['OPO','MLA','NAP','SPU','NCE','VCE'],
  ver:['RAK','HRG','CAI','DXB','AUH','IST','AYT'],
  alles:['BCN','LIS','PRG','BUD','FCO','PMI','RAK','AYT','ATH','NAP','DBV','VLC','MAD','SPU']
};
